[project]
name = "airsoft-prim-backend"
version = "0.1.0"
description = "Backend of the Airsoft portal."
readme = "README.md"
authors = [{ name = "Ruslan Bashinskiy", email = "main+development@oidaho.ru" }]
maintainers = []
classifiers = [
    "License :: GPLv3",
    "Operating System :: OS Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "fastapi>=0.141.1",
    "minio>=7.2.20",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.52",
    "uvicorn>=0.52.4",
]

[dependency-groups]
test = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-coverage>=0.0",
    "pytest-xdist>=3.8.0",
]


[tool.uv]
package = false
default-groups = ["test"]
